unicode-emojis:
  enabled: true # default option, set to false to disable default emojis...
  uri: "https://cinnamondev.github.io/minemoji/packs/twemoji-latest.zip"

custom-packs:
  # download json files from sources before loading.
  download: false # place jsons in plugins/minemoji/packs/*.json otherwise
  packs:
    - "https://cinnamondev.github.io/minemoji/packs/minemoji-latest.json" # Minemoji example pack
enforce-pack: true
# use minimessage!  :) remove entry to disable prompt
join-prompt: "This server uses resource pack to allow players to use emotes in gamechat :) <click:open_url:'https://github.com/cinnamondev/minemoji'><u><b><aqua>About</aqua></b></u></click>"