name: minemoji
version: '1.03'
main: com.github.cinnamondev.minemoji.Minemoji
api-version: '1.21'

dependencies:
  server:
    DiscordSRV:
      required: false
      load: BEFORE

permissions:
  minemoji.emoji:
    description: "use emojis"
    default: true
  minemoji.list:
    description: "list emojis"
    default: true